# Generated by Django 4.1.3 on 2022-11-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('reporter', models.CharField(max_length=50)),
                ('press', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('publication_time', models.DateTimeField()),
                ('publication_str', models.TextField()),
                ('result', models.TextField()),
                ('crawling_time', models.DateTimeField()),
            ],
        ),
    ]
