# Generated by Django 4.1.3 on 2022-11-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
