# Generated by Django 4.1.3 on 2022-11-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gubun',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
